title: Iván Montoya
logo: /assets/img/foto_perfil.jpeg
description: Student, data scientist, project manager, life learner and logistics passionate.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
